### ISSUE TITLE
13.0.0问题

### ISSUE THREAD

**Issue by hanghang0702** [ZhangZisu/ZenOnlineJudge#25]
**问题**
 当我在使用`Chrome Version 66.0.3359.139 (Official Build) (64-bit)`时，
访问`http://120.27.222.204/problems`并以`hanghang0702`登录。
服务器返回了一个问题页面：
![image](https://user-images.githubusercontent.com/26570964/40179595-501408ba-5a17-11e8-98fa-28e832835fc6.png)

**出现频率**
总是。

**系统**
- OS `Windows 10`
- Browser `Chrome Version 66.0.3359.139 (Official Build) (64-bit)`

**Comment by hanghang0702** [comment]
@ZhangZisu @zisu-zhang

**Comment by hanghang0702** [comment]
附上Console图片
![image](https://user-images.githubusercontent.com/26570964/40179849-d663d904-5a17-11e8-9bbd-a14d3c136791.png)

**Comment by ZhangZisu** [comment]
It's the not a bug. The problems is upgrading manually. They will be able to show when we finished the upgrade process.
