### ISSUE TITLE
建议在Blog中支持非数字题号

### ISSUE THREAD

**Issue by skylee03** [ZhangZisu/ZenOnlineJudge#46]
如题。一些OJ（如Codechef、AtCoder等）并没有纯数字题号，而在ZHOJ的Blog板块中提交带有英文字母的题号会被自动修改为0，造成不便。希望尽快修改。

**Comment by ZhangZisu** [comment]
OK. I'll fix it in next version. The database structure will be changed, too.

**Comment by ZhangZisu** [comment]
#47 Fixed this issue.
