### ISSUE TITLE
比赛缺少某个变量

### ISSUE THREAD

**Issue by mrsrz** [ZhangZisu/ZenOnlineJudge#62]
![default](https://user-images.githubusercontent.com/22657349/42409978-17bcaea6-8215-11e8-832e-0d5734f0dfb7.png)

**Comment by ZhangZisu** [comment]
Fixed. 3f7e952ff49d9fd47d1cde1c718154ab0f76a0e5-abfaa3a86e43a01b572642e7c3508b3ba8e9957f
